@startuml
skinParam ArrowColor Black
skinParam BackgroundColor White
skinParam actorBorderColor Black
skinparam actorBackgroundColor LightGray
skinParam componentBorderColor DarkGray
skinparam componentFontColor White
skinparam componentStereotypeFontColor LightGray
skinparam componentBackgroundColor #008292
skinparam databaseFontColor White
skinparam databaseBackgroundColor #008292
skinparam entityBackgroundColor LightGray
skinparam entityBorderColor DarkGray
skinparam queueBackgroundColor LightGray
skinparam queueBorderColor DarkGray
skinparam frameBorderColor DarkGray
skinparam frameBackgroundColor #f8f8f8
skinparam nodeBorderColor DarkGray
skinparam nodeBackgroundColor #f8f8f8
skinparam DefaultTextAlignment Center

together {
  actor Applicant
  actor Approver
  actor APIUser
}

node Proxy {
  component Apache << SSL Termination >>
}

node REMS {
  component WebApp << Single-page App >>

  component API
}

node AuthenticationProvider {
}

database Postgres

node EmailServer << SMTP >> {
}

node 3rdPartySystem << REST >> {
}


WebApp -left-> AuthenticationProvider : "OIDC, Haka"
WebApp -down-> API : "REST"
API -left-> AuthenticationProvider : "OIDC, Haka"
Applicant -down-> Apache
Approver -down-> Apache
Apache -down-> WebApp
APIUser .down.> Apache : "use with API-Key\nauthenticated against DB"
Apache .down.> API : "use with API-Key\nauthenticated against DB"
API -down-> Postgres
API -down-> EmailServer : "email notifications"
API -down-> 3rdPartySystem : "entitlement push"

@enduml
