@startuml
skinParam ArrowColor Black
skinParam BackgroundColor White
skinParam componentBorderColor Black
skinParam actorBorderColor Black
skinparam componentBackgroundColor LightGray
skinparam databaseBackgroundColor LightGray
skinparam actorBackgroundColor LightGray
skinparam Padding 5

actor Hakija
actor Hyväksyjä
actor APIKäyttäjä

node Tunnistautumispalvelu {
  component LDAP
  component Haka
}

node Palvelin {
  component WebApp <<Single-Page App>>
  component API <<REST>>
}

WebApp --> Tunnistautumispalvelu : "tunnistaa käyttäjän"

Hakija --> WebApp
Hyväksyjä --> WebApp
WebApp -> API : "     "
APIKäyttäjä --> API : "tunnistaa API-käyttäjän\ntietokantaa vasten"


node TietokantaPalvelin {
  database rems
}

node SähköpostiPalvelin {
  component email
}

API --> email : "lähettää sähköpostia"

node KolmannenOsapuolenPalvelin {
  component Vastaanottaja
}

API --> rems
API .> Vastaanottaja : "lähettää tiedot oikeuksista"
@enduml