DROP TABLE IF EXISTS rms_application_attachment_values;
--;;
DROP TABLE IF EXISTS rms_application_checkbox_values;
--;;
DROP TABLE IF EXISTS rms_application_form CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item_map CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item_string_values;
--;;
DROP TABLE IF EXISTS rms_application_form_meta CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_meta_map;
--;;
DROP TABLE IF EXISTS rms_application_license_approval_values;
--;;
DROP TABLE IF EXISTS rms_application_referee_invite_values;
--;
DROP TABLE IF EXISTS rms_application_referee_values;
--;;
DROP TABLE IF EXISTS rms_application_text_values;
--;;
DROP TABLE IF EXISTS rms_attachment CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_approvers;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_catid_overflow;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_free_comment_values;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_licenses;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_member_invite_values;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_members;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_metadata;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_predecessor;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_publications;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_reviewers;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_state CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_state_reason;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_localization;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_predecessor;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_state;
--;;
DROP TABLE IF EXISTS rms_entitlement;
--;;
DROP TABLE IF EXISTS rms_entitlement_ebi;
--;;
DROP TABLE IF EXISTS rms_entitlement_saml;
--;;
DROP TABLE IF EXISTS rms_entitlement_saml_migration;
--;;
DROP TABLE IF EXISTS rms_invitations;
--;;
DROP TABLE IF EXISTS rms_license CASCADE;
--;;
DROP TABLE IF EXISTS rms_license_localization;
--;;
DROP TABLE IF EXISTS rms_license_references;
--;;
DROP TABLE IF EXISTS rms_manifestations;
--;;
DROP TABLE IF EXISTS rms_resource CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_close_period;
--;;
DROP TABLE IF EXISTS rms_resource_licenses;
--;;
DROP TABLE IF EXISTS rms_resource_link_location;
--;;
DROP TABLE IF EXISTS rms_resource_mf_ebi_dac_target;
--;;
DROP TABLE IF EXISTS rms_resource_mf_saml_target;
--;;
DROP TABLE IF EXISTS rms_resource_prefix CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_form_editing;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_members;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_updates;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_application;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_certificates;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_close_period;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_default_form;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_link_location;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_mf_ebi;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_owners;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_refresh_period;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_reporters;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_state;
--;;
DROP TABLE IF EXISTS rms_resource_refresh_period;
--;;
DROP TABLE IF EXISTS rms_resource_state;
--;;
DROP TABLE IF EXISTS rms_user_selection_names;
--;;
DROP TABLE IF EXISTS rms_user_selections;
--;;
DROP TABLE IF EXISTS rms_workflow CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_approver_options;
--;;
DROP TABLE IF EXISTS rms_workflow_approvers;
--;;
DROP TABLE IF EXISTS rms_workflow_licenses;
--;;
DROP TABLE IF EXISTS rms_workflow_reviewers;
--;;
DROP TABLE IF EXISTS rms_workflow_round_min;
--;;
DROP TYPE scope;
--;;
DROP TYPE itemtype;
--;;
DROP TYPE approval_status;
--;;
DROP TYPE license_status;
--;;
DROP TYPE license_state;
--;;
DROP TYPE application_state;
--;;
DROP TYPE item_state;
--;;
DROP TYPE prefix_state;
--;;
DROP TYPE license_type;
--;;
DROP TYPE reviewers_state;
