DROP TABLE IF EXISTS rms_application_attachment_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_checkbox_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item_map CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_item_string_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_meta CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_form_meta_map CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_license_approval_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_referee_invite_values CASCADE;
--;
DROP TABLE IF EXISTS rms_application_referee_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_application_text_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_attachment CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_approvers CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_catid_overflow CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_free_comment_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_licenses CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_member_invite_values CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_members CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_metadata CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_predecessor CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_publications CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_reviewers CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_state CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_application_state_reason CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_localization CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_predecessor CASCADE;
--;;
DROP TABLE IF EXISTS rms_catalogue_item_state CASCADE;
--;;
DROP TABLE IF EXISTS rms_entitlement CASCADE;
--;;
DROP TABLE IF EXISTS rms_entitlement_ebi CASCADE;
--;;
DROP TABLE IF EXISTS rms_entitlement_saml CASCADE;
--;;
DROP TABLE IF EXISTS rms_entitlement_saml_migration CASCADE;
--;;
DROP TABLE IF EXISTS rms_invitations CASCADE;
--;;
DROP TABLE IF EXISTS rms_license CASCADE;
--;;
DROP TABLE IF EXISTS rms_license_localization CASCADE;
--;;
DROP TABLE IF EXISTS rms_license_references CASCADE;
--;;
DROP TABLE IF EXISTS rms_manifestations CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_close_period CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_licenses CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_link_location CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_mf_ebi_dac_target CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_mf_saml_target CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_form_editing CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_members CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_allow_updates CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_application CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_certificates CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_close_period CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_default_form CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_link_location CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_mf_ebi CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_owners CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_refresh_period CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_reporters CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_prefix_state CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_refresh_period CASCADE;
--;;
DROP TABLE IF EXISTS rms_resource_state CASCADE;
--;;
DROP TABLE IF EXISTS rms_user_selection_names CASCADE;
--;;
DROP TABLE IF EXISTS rms_user_selections CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_approver_options CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_approvers CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_licenses CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_reviewers CASCADE;
--;;
DROP TABLE IF EXISTS rms_workflow_round_min CASCADE;
--;;
DROP TYPE scope;
--;;
DROP TYPE itemtype;
--;;
DROP TYPE approval_status;
--;;
DROP TYPE license_status;
--;;
DROP TYPE license_state;
--;;
DROP TYPE reviewers_state;
--;;
DROP TYPE application_state;
--;;
DROP TYPE item_state;
--;;
DROP TYPE prefix_state;
--;;
DROP TYPE license_type;
