drop table workflow_round_min;
--;;
drop table workflow_approver_options;
--;;
drop table workflow_actors;
--;;
drop table resource_state;
--;;
drop table resource_refresh_period;
--;;
drop table resource_close_period;
--;;
drop table catalogue_item_application_licenses;
--;;
drop table catalogue_item_application_items;
--;;
drop table application_text_values;
--;;
drop table application_license_approval_values;
--;;
drop table application_form_item_options;
--;;
drop table application_form_item_map;
--;;
drop table application_form_item_localization;
--;;
drop table application_form_item;
--;;
drop table application_form;
